@localhost=localhost:4004/odata/v4/main

@id= a6118c05-7d0c-4520-8bd1-245480242a73
@CustomerId= 27677234-34b1-4807-87ba-018821fe069a
@productId= 87654321-12ab-34cd-56ef-1234567890ab

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###
POST  http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customerId": "{{CustomerId}}",
    "items": [
        {
            "id": "",
            "header": "{{id}}",
            "productId": "{{productId}}",
            "quantity": 2,
            "price": 19.99
        },
        {
            "id": "",
            "header": "{{id}}",
            "productId": "12345678-90ab-cdef-1234-567890abcdef",
            "quantity": 1,
            "price": 9.99
        }
    ]
}

###

DELETE http://localhost:4004/odata/v4/main/SalesOrderHeaders(id="1234")
content -type: application/json
###

# Buscar todos os pedidos maiores ou iguais a 2 milhões
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount ge 2000000

###

# Buscar todos os pedidos menores ou iguais a 200k
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount le 200000

###

# Expandindo os items
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount le 200000