@localhost=localhost:4004/odata/v4/main

@id= a6118c05-7d0c-4520-8bd1-245480242a73
@CustomerId= 27677234-34b1-4807-87ba-018821fe069a
@productId= 22816525-ef02-4ca7-8b24-611c4cc3b9e9

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic ZGFuaWxvOjEyMzQ1Ng==

###
POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic ZGFuaWxvOjEyMzQ1Ng==

{
  "customer_id": "{{CustomerId}}",
  "items": [
    {
      "product_id": "{{productId}}",
      "quantity": 2,
      "price": 19.99
    },
    {
      "product_id": "22816517-093d-42b2-a7da-74426368e453",
      "quantity": 1,
      "price": 9.99
    }
  ]
}

###

DELETE http://localhost:4004/odata/v4/main/SalesOrderHeaders(id="1234")
Content-Type: application/json
Authorization: Basic ZGFuaWxvOjEyMzQ1Ng==

###

# Buscar todos os pedidos maiores ou iguais a 2 milhões
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount ge 2000000

###

# Buscar todos os pedidos menores ou iguais a 200k
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount le 200000

###

# Expandindo os items
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount le 200000

###

# Expandindo os items, produtos e customers
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$expand=items($expand=product),customer

###

# Expandindo os items, produtos e customers
GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$expand=items($expand=product),customer

###
# Expandindo os items, produtos, customers e filtrando
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity le 30),customer

###
# Selecionar somente customer e id do sales order header
GET http://{{localhost}}/SalesOrderHeaders?$select=customer&$expand=customer($select=email)

###
# Descobrindo a quantidade de registros
GET http://{{localhost}}/SalesOrderHeaders/$count

###
# Paginando os registros
GET http://{{localhost}}/SalesOrderHeaders?$skip=10&$top=5

###

# Buscando dados com $search
GET http://{{localhost}}/SalesOrderHeaders?$search=firstName2
Content-Type: application/json

###

# Ordenando dados com $orderby
GET http://{{localhost}}/SalesOrderHeaders?$orderby=firstName desc,lastName
Content-Type: application/json

### Funcionalidade de Clonar Pedidos

POST http://{{localhost}}/SalesOrderHeaders(26204170-b136-4537-9b20-e913dec61e09)/cloneSalesOrder
Content-Type: application/json
Authorization: Basic ZGFuaWxvOjEyMzQ1Ng==

{
  
}
